### PR TITLE
minor fix in greeting bot: close #32

### LINKED ISSUE #32: Fix Greeting Bot
**Describe the bug**
Fix .yml file for greeting bot, currently failing.

.yml file shows this:

Screen Shot 2021-10-28 at 11 24 38 AM

but should show this:

Screen Shot 2021-10-28 at 11 27 47 AM

**Tasks**
Update .yml file with appropriate formatting as shown. 

in future using linting in editor (VSCode) can also check errors with a tool like http://www.yamllint.com/

### PR DESCRIPTION
**Pull request by Fiewor**
Signed-off-by: John Fiewor <johnfiewor@gmail.com>

Contributes to #32  (add issue number here. i.e. `#302`)

## What did you do?
Correct indentation error in greetings.yml
## Why did you do it?
To ensure the greeting bot works correctly
## How have you tested it?
No
## Were docs updated if needed?
- [x] No
- [ ] Yes
- [ ] N/A

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new console logs
- [x] Fixes entire issue
- [ ] Partial fix for issue

### CODE REVIEW

**Comment by demilolu** [comment]
@Fiewor can you address the issue above with the greetings check>

**Comment by Fiewor** [comment]
> @Fiewor can you address the issue with the greetings check>

Alright. Will do

**Comment by Fiewor** [comment]
> > > @Fiewor can you address the issue with the greetings check>
> > 
> > 
> > Alright. Will do
> 
> All done @demilolu

Hi @demilolu just a reminder that I've resolved this and you can now review it

**Review by demilolu — APPROVED** [review]
spacing fixed. approved.

**Pull request merged**
